### PR TITLE
Update for PIXI 7+

### LINKED ISSUE #6: Cannot invoke constructor?
image
<br>Here is the implements:
image
<br>
My project is using vite for client rendering and here is my tsconfig.json: https://pastebin.com/R1AydsBT.
PIXI version: "^7.1.0"

### PR DESCRIPTION
**Pull request by reececomo**
Enables support for PIXI 7+ and fixes #6 

This is a breaking change, so might want to consider releasing as a new major version?

👍

### CODE REVIEW

**Comment by Azaeres** [comment]
Thanks for the PR!

One issue I've found with this update is that the joystick behavior isn't exactly the same. Before, onDragMove would track all over the screen. Now, it tracks only when your finger/thumb is over the joystick element. This could lead to a frustrating playing experience.

Is that your experience too? Any suggestions?

**Comment by reececomo** [comment]
I didn't realise that was desirable - for our game we actually only want it to track when its over the joystick (like a real one).

I'll leave this PR up as a reference and feel free to make any changes 👍

**Comment by Azaeres** [comment]
Sorry, I found this behavior a bit hard to describe. I mean that in the previous version you tap directly **onto** the joystick like you're saying, but then are able to **drag** off the joystick, even to the edges of the screen, and the joystick will still be tracking in real-time. In this version (as well as in my own tests), the tracking stops at the edge of the joystick element.

My understanding is that Pixi 7 changed the way events propagate in order to make it more consistent with the way events propagate in the DOM, so it does make sense that this behavior would be affected. My guess is that, to make the two versions behave the same, the event handling might need to happen at a higher level than the joystick itself.

**Comment by reececomo** [comment]
That doesn't appear to happen for me 👍 Although I'm using a slight fork of this code.

**Pull request closed without merging**
